name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - diberry/static-web-app-push

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_DUNE_0E6BF500F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_build_command: "npm build"
          app_location: "/src" # App source code path
          app_artifact_location: "/build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env: # Or as an environment variable
          REACT_APP_ComputerVisionKey: ${{ secrets.REACT_APP_ComputerVisionKey }}
          REACT_APP_ComputerVisionEndPoint: ${{ secrets.REACT_APP_ComputerVisionEndPoint }}
